### PR TITLE
Feature/template upgrades

### PR DESCRIPTION
**Pull request by BenDiuguid**
This upgrades the templates mainly by adding `eslint` support as well as updating/cleaning up the `package.json` and `webpack.config`'s.

Also `ng6 serve` calls `npm run serve` and `ng6 build` calls `npm run build`

### CODE REVIEW

**Comment by johnrjj** [comment]
is this repo eligible for hacktoberfest?

**Comment by BenDiuguid** [comment]
I was hoping so, I think you just have to sign up, then make 4 PR's on GitHub.

>If you make four pull requests by October 31st, you'll get the satisfaction of sharing your code >with the world—and a t-shirt, of course.
> -[Hacktoberfest is back](https://github.com/blog/2260-hacktoberfest-is-back)

**Comment by johnrjj** [comment]
I thought you had to label the issue with Hacktoberfest, no? (I may be incorrect)

**Comment by BenDiuguid** [comment]
Everything I've seen (and I tried to figure this out) seems to say it can be any open source project on GitHub. You just need to submit 4 PR's. 😄

**Comment by asleepinglion** [comment]
Thanks! Merged, but still need to update npm.

**Pull request merged**
